### ISSUE TITLE
Where is the code for RHOMLDA and HOMLDA?

### ISSUE THREAD

**Issue by llvm-x86** [Cagri-Ozdemir/High-Order-Multilinear-Discriminant-Analysis-HOMLDA-#1]
.

**Comment by Cagri-Ozdemir** [comment]
https://github.com/Cagri-Ozdemir/High-Order-Multilinear-Discriminant-Analysis

**Comment by Cagri-Ozdemir** [comment]
MLDA-dct, MLDA-dwt, MLDA-dft are our proposed methods!

**Comment by llvm-x86** [comment]
I see, sorry for the confusion.
